### ISSUE TITLE
[Tracker] release commands

### ISSUE THREAD

**Issue by profclems** [profclems/glab#366]
`glab` currently only supports listing releases. There are other releases endpoints available in the [Releases API](https://docs.gitlab.com/ce/api/releases) that can be incorporated into `glab` as subcommands under the `release` command
- [x] `create`:     Create a new release - (https://docs.gitlab.com/ce/api/releases/#create-a-release)
 
- [x] `delete`:     Delete a release - (https://docs.gitlab.com/ce/api/releases/#delete-a-release)
     - Usage format should be `glab release delete <tag> [flags]`
     - `<tag>` is required
     - User must be prompted to confirm deletion
     - `-y, --yes` to skip the confirmation prompt

- [x] `list`:       List releases in a repository/project - (https://docs.gitlab.com/ce/api/releases/#list-releases)
   - [x] Done
   - [x] Released
- [x] `upload`:     Upload assets to a release !
     - The releases API does not allow uploading assets but only the asset link (https://gitlab.com/gitlab-org/gitlab/-/issues/17838)
     - We may have to utilize the [Upload File API](https://docs.gitlab.com/ee/api/projects.html#upload-a-file)

- [x] `download`:   Download release assets 

- [x] `view`:       View information about a release - (https://docs.gitlab.com/ce/api/releases/#get-a-release-by-a-tag-name)
     - Should follow the usage format `glab release view [<tag>] [flags]`
     - If the tag_name (`<tag>`) is not explicitly set, the latest release in the project is shown.

This issue also serves as a tracker and each task will be marked as done as PRs are created and merged

**Comment by profclems** [comment]
Another limitation with the asset upload is the file size limit which is <=10mb. There's an open issue on this here https://gitlab.com/gitlab-org/gitlab/-/issues/20060

**Comment by clemsbot** [comment]
This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.

**Comment by clemsbot** [comment]
This issue has been automatically marked as stale because it has not had recent activity. We haven't had the time to address it yet, but we want to keep it open. This message is just a reminder for us to help triage issues.
